"""
Seat service — stub implementation with representative sample data.
Replace with real database queries when integrating with ProM's backend.
"""
from __future__ import annotations
from datetime import datetime, timezone, date
from typing import Optional
from app.models.seat import Seat, SeatListResponse, SeatSearchParams, CandidateStatus, SeatType, StatusBreakdown

_now = datetime.now(timezone.utc)

# ── Stub seat data ─────────────────────────────────────────────────────────────
_SEATS: list[Seat] = [
    Seat(
        seat_id="SEAT-001",
        title="Senior Full-Stack Developer",
        client_name="TechCorp Digital Transformation",
        owner_notes_id="Marcus Chen/Innovation Lab/IBM",
        service="Application Development",
        requested_band_high="8",
        requested_band_low="7",
        contract_owning_country="United States",
        work_location="Remote",
        work_remotely=True,
        sector="Financial Services",
        industry="Banking",
        last_updated=datetime(2025, 6, 15, tzinfo=timezone.utc),
        days_since_update=12,
        candidate_status=CandidateStatus.PROPOSED,
        profs_in_play=18,
        status_breakdown=StatusBreakdown(proposed=14, selected=4),
        positions_still_needed=3,
        start_date=date(2026, 1, 15),
        clearance_needed=None,
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-002",
        title="Cloud Infrastructure Engineer",
        client_name="Global Finance Modernization",
        owner_notes_id="Sarah Williams/Cloud Center/IBM",
        service="Cloud Engineering",
        requested_band_high="8",
        requested_band_low="7",
        contract_owning_country="United States",
        work_location="New York",
        work_remotely=True,
        sector="Financial Services",
        industry="Investment Banking",
        last_updated=datetime(2025, 7, 1, tzinfo=timezone.utc),
        days_since_update=5,
        candidate_status=CandidateStatus.SELECTED,
        profs_in_play=6,
        status_breakdown=StatusBreakdown(proposed=1, selected=5),
        positions_still_needed=1,
        start_date=date(2026, 2, 1),
        clearance_needed=None,
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=True,
        is_available=False,
        mismatch_flag=True,
        ai_recommendation_note="Candidate already Selected — verify if this seat should be closed.",
    ),
    Seat(
        seat_id="SEAT-003",
        title="Data Science Lead",
        client_name="Healthcare Systems Integration",
        owner_notes_id="David Rodriguez/Platform Team/IBM",
        service="Analytics & AI",
        requested_band_high="9",
        requested_band_low="8",
        contract_owning_country="United States",
        work_location="Boston",
        work_remotely=False,
        sector="Healthcare",
        industry="Medical Technology",
        last_updated=datetime(2025, 6, 28, tzinfo=timezone.utc),
        days_since_update=8,
        candidate_status=None,
        profs_in_play=14,
        status_breakdown=StatusBreakdown(proposed=14),
        positions_still_needed=2,
        start_date=date(2025, 12, 1),
        clearance_needed="Public Trust",
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-004",
        title="DevOps Engineer",
        client_name="Retail Analytics Platform",
        owner_notes_id="Jennifer Kim/Data Solutions/IBM",
        service="Platform Engineering",
        requested_band_high="7",
        requested_band_low="6",
        contract_owning_country="United States",
        work_location="San Francisco",
        work_remotely=True,
        sector="Retail",
        industry="E-commerce",
        last_updated=datetime(2025, 4, 10, tzinfo=timezone.utc),
        days_since_update=67,
        candidate_status=CandidateStatus.NOT_SELECTED,
        profs_in_play=9,
        status_breakdown=StatusBreakdown(proposed=6, not_selected=3),
        positions_still_needed=1,
        start_date=date(2026, 3, 1),
        clearance_needed=None,
        seat_type=SeatType.FORMAL,
        is_stale=True,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-005",
        title="Solutions Architect",
        client_name="Energy Grid Optimization",
        owner_notes_id="Marcus Chen/Innovation Lab/IBM",
        service="Solution Architecture",
        requested_band_high="9",
        requested_band_low="8",
        contract_owning_country="United States",
        work_location="Chicago",
        work_remotely=False,
        sector="Manufacturing",
        industry="Energy",
        last_updated=datetime(2025, 7, 3, tzinfo=timezone.utc),
        days_since_update=2,
        candidate_status=CandidateStatus.PROPOSED,
        profs_in_play=11,
        status_breakdown=StatusBreakdown(proposed=11),
        positions_still_needed=2,
        start_date=date(2026, 1, 20),
        clearance_needed=None,
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=True,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-006",
        title="Backend API Developer",
        client_name="TechCorp Digital Transformation",
        owner_notes_id="Sarah Williams/Cloud Center/IBM",
        service="Application Development",
        requested_band_high="7",
        requested_band_low="6",
        contract_owning_country="United States",
        work_location="Remote",
        work_remotely=True,
        sector="Financial Services",
        industry="FinTech",
        last_updated=datetime(2025, 6, 20, tzinfo=timezone.utc),
        days_since_update=16,
        candidate_status=None,
        profs_in_play=22,
        status_breakdown=StatusBreakdown(proposed=18, selected=2, not_selected=2),
        positions_still_needed=4,
        start_date=date(2025, 11, 15),
        clearance_needed="Secret",
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-007",
        title="ML Engineer",
        client_name="Healthcare Systems Integration",
        owner_notes_id="David Rodriguez/Platform Team/IBM",
        service="AI & Machine Learning",
        requested_band_high="8",
        requested_band_low="7",
        contract_owning_country="United States",
        work_location="Remote",
        work_remotely=True,
        sector="Healthcare",
        industry="Pharmaceuticals",
        last_updated=datetime(2025, 6, 5, tzinfo=timezone.utc),
        days_since_update=31,
        candidate_status=CandidateStatus.PROPOSED,
        profs_in_play=15,
        status_breakdown=StatusBreakdown(proposed=15),
        positions_still_needed=2,
        start_date=date(2026, 2, 15),
        clearance_needed=None,
        seat_type=SeatType.REAL,
        is_stale=True,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-008",
        title="Frontend Engineer",
        client_name="Retail Analytics Platform",
        owner_notes_id="Jennifer Kim/Data Solutions/IBM",
        service="UX Engineering",
        requested_band_high="7",
        requested_band_low="6",
        contract_owning_country="United States",
        work_location="New York",
        work_remotely=True,
        sector="Retail",
        industry="Consumer Goods",
        last_updated=datetime(2025, 7, 2, tzinfo=timezone.utc),
        days_since_update=4,
        candidate_status=CandidateStatus.WITHDRAWN,
        profs_in_play=5,
        status_breakdown=StatusBreakdown(proposed=3, withdrawn=2),
        positions_still_needed=3,
        start_date=date(2026, 1, 10),
        clearance_needed=None,
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=True,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-009",
        title="Security Architect",
        client_name="Global Finance Modernization",
        owner_notes_id="Marcus Chen/Innovation Lab/IBM",
        service="Cybersecurity",
        requested_band_high="9",
        requested_band_low="8",
        contract_owning_country="United States",
        work_location="Remote",
        work_remotely=True,
        sector="Financial Services",
        industry="Banking",
        last_updated=datetime(2025, 3, 15, tzinfo=timezone.utc),
        days_since_update=92,
        candidate_status=CandidateStatus.PROPOSED,
        profs_in_play=7,
        status_breakdown=StatusBreakdown(proposed=7),
        positions_still_needed=1,
        start_date=date(2026, 4, 1),
        clearance_needed="Secret",
        seat_type=SeatType.REAL,
        is_stale=True,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-010",
        title="QA Automation Lead",
        client_name="TechCorp Digital Transformation",
        owner_notes_id="Sarah Williams/Cloud Center/IBM",
        service="Quality Engineering",
        requested_band_high="8",
        requested_band_low="7",
        contract_owning_country="United States",
        work_location="San Francisco",
        work_remotely=True,
        sector="Financial Services",
        industry="FinTech",
        last_updated=datetime(2025, 6, 25, tzinfo=timezone.utc),
        days_since_update=11,
        candidate_status=CandidateStatus.SELECTED,
        profs_in_play=4,
        status_breakdown=StatusBreakdown(proposed=1, selected=3),
        positions_still_needed=2,
        start_date=date(2026, 2, 1),
        clearance_needed="Public Trust",
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=False,
        is_available=False,
        mismatch_flag=True,
        ai_recommendation_note="Multiple candidates Selected — verify capacity.",
    ),
    Seat(
        seat_id="SEAT-011",
        title="Product Manager",
        client_name="Healthcare Systems Integration",
        owner_notes_id="David Rodriguez/Platform Team/IBM",
        service="Product Management",
        requested_band_high="9",
        requested_band_low="8",
        contract_owning_country="United States",
        work_location="Boston",
        work_remotely=False,
        sector="Healthcare",
        industry="Health Insurance",
        last_updated=datetime(2025, 7, 5, tzinfo=timezone.utc),
        days_since_update=1,
        candidate_status=None,
        profs_in_play=19,
        status_breakdown=StatusBreakdown(proposed=19),
        positions_still_needed=1,
        start_date=date(2025, 12, 15),
        clearance_needed=None,
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=True,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-012",
        title="Database Administrator",
        client_name="Energy Grid Optimization",
        owner_notes_id="Jennifer Kim/Data Solutions/IBM",
        service="Database Services",
        requested_band_high="7",
        requested_band_low="6",
        contract_owning_country="United States",
        work_location="Chicago",
        work_remotely=True,
        sector="Manufacturing",
        industry="Energy",
        last_updated=datetime(2025, 5, 1, tzinfo=timezone.utc),
        days_since_update=54,
        candidate_status=CandidateStatus.NOT_SELECTED,
        profs_in_play=8,
        status_breakdown=StatusBreakdown(proposed=5, not_selected=3),
        positions_still_needed=1,
        start_date=date(2026, 5, 1),
        clearance_needed="Top Secret",
        seat_type=SeatType.FORMAL,
        is_stale=True,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-013",
        title="Business Analyst",
        client_name="Retail Analytics Platform",
        owner_notes_id="Marcus Chen/Innovation Lab/IBM",
        service="Business Analysis",
        requested_band_high="7",
        requested_band_low="6",
        contract_owning_country="United States",
        work_location="Remote",
        work_remotely=True,
        sector="Retail",
        industry="E-commerce",
        last_updated=datetime(2025, 6, 30, tzinfo=timezone.utc),
        days_since_update=6,
        candidate_status=CandidateStatus.PROPOSED,
        profs_in_play=12,
        status_breakdown=StatusBreakdown(proposed=12),
        positions_still_needed=2,
        start_date=date(2026, 1, 5),
        clearance_needed=None,
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-014",
        title="Network Engineer",
        client_name="TechCorp Digital Transformation",
        owner_notes_id="Sarah Williams/Cloud Center/IBM",
        service="Network Infrastructure",
        requested_band_high="8",
        requested_band_low="7",
        contract_owning_country="United States",
        work_location="New York",
        work_remotely=False,
        sector="Financial Services",
        industry="Banking",
        last_updated=datetime(2025, 4, 5, tzinfo=timezone.utc),
        days_since_update=71,
        candidate_status=None,
        profs_in_play=3,
        status_breakdown=StatusBreakdown(proposed=3),
        positions_still_needed=1,
        start_date=date(2026, 3, 15),
        clearance_needed="Public Trust",
        seat_type=SeatType.FORMAL,
        is_stale=True,
        has_applied=True,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
    Seat(
        seat_id="SEAT-015",
        title="Scrum Master",
        client_name="Global Finance Modernization",
        owner_notes_id="David Rodriguez/Platform Team/IBM",
        service="Agile Delivery",
        requested_band_high="8",
        requested_band_low="7",
        contract_owning_country="United States",
        work_location="Remote",
        work_remotely=True,
        sector="Financial Services",
        industry="Investment Banking",
        last_updated=datetime(2025, 6, 18, tzinfo=timezone.utc),
        days_since_update=18,
        candidate_status=CandidateStatus.PROPOSED,
        profs_in_play=14,
        status_breakdown=StatusBreakdown(proposed=10, selected=4),
        positions_still_needed=3,
        start_date=date(2026, 2, 20),
        clearance_needed=None,
        seat_type=SeatType.REAL,
        is_stale=False,
        has_applied=False,
        is_available=True,
        mismatch_flag=False,
        ai_recommendation_note=None,
    ),
]


def search_seats(params: SeatSearchParams) -> SeatListResponse:
    results = list(_SEATS)

    if params.query:
        q = params.query.lower()
        results = [
            s for s in results
            if q in s.title.lower()
            or q in s.client_name.lower()
            or q in s.service.lower()
        ]
    if params.work_location:
        results = [s for s in results if params.work_location.lower() in s.work_location.lower()]
    if params.work_remotely is not None:
        results = [s for s in results if s.work_remotely == params.work_remotely]
    if params.sector:
        results = [s for s in results if params.sector.lower() in s.sector.lower()]
    if params.band:
        results = [s for s in results if s.requested_band_high == params.band or s.requested_band_low == params.band]
    if params.owner_notes_id:
        results = [s for s in results if params.owner_notes_id.lower() in s.owner_notes_id.lower()]

    total = len(results)
    start = (params.page - 1) * params.per_page
    end = start + params.per_page

    return SeatListResponse(
        total=total,
        page=params.page,
        per_page=params.per_page,
        seats=results[start:end],
    )


def get_seat_by_id(seat_id: str) -> Optional[Seat]:
    return next((s for s in _SEATS if s.seat_id == seat_id), None)


def get_all_seats() -> list[Seat]:
    """Get all seats (for owner portal filtering)"""
    return _SEATS
